# hunting for attractors, source https://blog.k2h.se/post/hunting-for-attractors/

```{r setup}
library(tidyverse)
library(future)
library(furrr)
library(cluster)
library(cowplot)

plan(multisession)

# functions
source("R/attractors_functions.r")

# options
options(dplyr.summarise.inform=FALSE)
update_geom_defaults("point", list(size = 0.1, stroke = 0, shape = 16))

# parameters
scale_ink <- scale_color_gradientn(
  colors = c("white","grey60","#036564", "#033649", "#031634")
  ) 

scale_bg <- scale_colour_gradient(low="grey80", high="black")
scale_grey <- scale_colour_gradient(low="grey60", high="black")
scale_white <- scale_colour_gradient(low="grey60", high="white")
scale_cell <- scale_color_gradientn(colors = c("#22607e","#1a4553","#2f2354"), guide = "none") 

color_ink <- "#124270"
color_old <- "#FEFAEE"
color_bg_cell <- "#d0dfe6"

```


```{r explore_quadratic, eval=FALSE}
set.seed(1)

# sample parameter space and filter interesting solutions based on Henrik Lindberg method
# L(quadratic_2d, henon_a, 0.01, 0.01)
# L(quadratic_2d, rep(0, 12), 0.01, 0.01)
table_set <- tibble(pattern = 1:1E5) %>%
  mutate(a = map(pattern, ~ round(runif(12, -1.5, 1.5), 2))) %>%
  mutate(L_val = future_map_dbl(a, ~ L(quadratic_2d, ., 0, 0))) %>%
  filter(L_val > 0)

# export
saveRDS(table_set, file="data/attractor_parameter_set.rds", compress="gzip")

```

```{r analyse_density, eval=FALSE}
table_set <- read_rds("data/attractor_parameter_set.rds")

# add a metric for filtering of scatterplot point density
data_set <- table_set %>%
  compute_grid_data(5000) %>% 
  mutate(density = map_int(xy, density_quantile, gridsize=20))

# plot
plot_set_keep <- data_set %>% filter(density >= 90) %>% render_grid()
plot_set_discard <- data_set %>% filter(density < 90) %>% render_grid()
plot_set_volume <- data_set %>% filter(density >= 200) %>% render_grid()

plot_set_focus <- data_set %>%
  filter(pattern == 38286) %>%
  compute_grid_data(5E5) %>%
  render_grid()

ggsave(
  plot_set_keep + facet_wrap(vars(pattern), ncol=20),
  file="./R/figures/attractor_set_keep.png",
  dpi=200, width = 7, height = 20, scale = 2)

ggsave(
  plot_set_discard + facet_wrap(vars(pattern), ncol=20),
  file="./R/figures/attractor_set_discard.png",
  dpi=200, width = 7, height = 20, scale = 2)

```


```{r analyse_cluster, eval=FALSE}
# run a cluster analysis to identify set of solutions with similar features

n_cluster = 25

# load parameter sets
table_set <- read_rds("data/attractor_parameter_set.rds")

data_cluster <- table_set %>%
  compute_grid_data(2000) %>% 
  mutate(
    density = map_int(xy, density_quantile, gridsize=20),
    heatmap = future_map(xy, density_heatmap, gridsize=20, bw=1/10),
    plot = future_map(xy, render_grid, output="single")
    )

# cluster analysis on parameters space (stupid)
matrix_input <- data_cluster %>% pull(a, name=pattern) %>% bind_rows() %>% t() 
cluster_input <- pam(matrix_input, k=n_cluster, pamonce = 5)
data_cluster <- data_cluster %>% mutate(cluster_input = cluster_input$cluster)

# cluster analysis on output space : heatmaps based on 2D point density distribution (better)
matrix_output <- data_cluster %>% 
  select(pattern, heatmap) %>% unnest(heatmap) %>%
  pivot_wider(names_from = c(x, y), values_from = value) %>% 
  select(-pattern) %>% as.matrix()

cluster_output <- pam(matrix_output, k = n_cluster, pamonce = 5)
data_cluster <- data_cluster %>% mutate(cluster_output = cluster_output$cluster)

# basic density feature allows to roughly separate dispersed and close-packed graphs
plot_density <- data_cluster %>%
  ggplot(aes(x=density, y=as.factor(pattern))) +
  geom_point() + geom_vline(xintercept = 100) + theme_bw() + 
  theme(axis.text.y = element_blank())

# view clustering result on graph filtered to avoid complex solutions
data_cluster_subset <- data_cluster %>% filter(density < 170) 

# plot heatmaps that represent graphs to cluster  
plot_heatmap <- data_cluster_subset %>% 
  slice_sample(n=49) %>% 
  unnest(heatmap) %>% 
  ggplot(aes(x, y, fill=value)) + 
  geom_raster() + facet_wrap(vars(pattern)) +
  scale_fill_viridis_c()

# similar parameter set do not lead to similar graphs, seems expected...
data_plot_input <- data_cluster_subset %>% 
  group_by(cluster_input) %>% 
  slice_sample(n=20) %>% nest() %>% 
  mutate(plot_list=map(data, ~ plot_grid(plotlist = .x$plot)))

plot_cluster_input <- plot_grid(plotlist = data_plot_input$plot_list, labels=1:n_cluster, scale=0.8)

ggsave(
  plot_cluster_input,
  file="./R/figures/attractor_set_cluster_parameters.png",
  dpi=200, width = 7, height = 10, scale = 2)

# kmeans clustering seems to mainly get graph global shape and orientation
data_plot_output <- data_cluster_subset %>% 
  group_by(cluster_output) %>% 
  slice_sample(n=20) %>% nest() %>% 
  mutate(plot_list=map(data, ~ plot_grid(plotlist = .x$plot)))

plot_cluster_output <- plot_grid(plotlist = data_plot_output$plot_list, labels=1:n_cluster, scale=0.8)

ggsave(
  plot_cluster_output,
  file="./R/figures/attractor_set_cluster_density.png",
  dpi=200, width = 7, height = 10, scale = 2)

```


```{r analyse_glyphs, eval=FALSE}
table_set <- read_rds("data/attractor_parameter_set.rds")

# plot set of graphs based on density criteria (1379/1773)
plot_set_characters <- table_set %>%
  compute_grid_data(iterations = 2000) %>% 
  mutate(density = map_int(xy, density_quantile, gridsize=20)) %>% 
  filter(density < 170) %>%
  render_grid(color=color_ink)

ggsave(
  plot_set_characters + facet_wrap(vars(pattern), ncol=20),
  file=glue::glue("./R/figures/attractor_set_characters.png"),
  dpi=300, width=7, height=20, scale=2)

# manually select interesting glyphs on this list
list_selected_characters <- c(
  31, 75, 737, 1556, 2051, 2128, 2669, 2691, 3292, 3603,
  3723, 3788, 4016, 4449, 5797, 13767, 14315, 14603, 15157, 16089, #11813
  16638, 20341, 21548, 21847, 21895, 23384, 24190, 24586, 24939, 24943,
  25319, 25384, 25546, 25990, 25998, 26367, 27606, 29238, 30093, 30647,
  31870, 33263, 33905, 37160, 37461, 37513, 37657, 39385, 39768, 43188, 
  43796, 44876, 45284, 45485, 46358, 46507, 48313, 48534, 48733, 49585
)

plot_set_characters_selected <- table_set %>%
  filter(pattern %in% list_selected_characters) %>% 
  compute_grid_data(iterations = 2000) %>% 
  render_grid(color=color_ink) 

ggsave(
  plot_set_characters_selected + facet_wrap(vars(pattern), ncol=10),
  file=glue::glue("./R/figures/attractor_set_characters_selected.png"),
  dpi=300, width=210, height=295, scale=1, units="mm")

# generate a low resolution sequence list of characters to export
data_characters <- table_set %>%
  filter(pattern %in% list_selected_characters) %>% 
  compute_grid_data(iterations = 1000) %>% 
  mutate(
    plot = map(xy, render_grid, color=color_ink, output="single")
  )

write_rds(data_characters, glue::glue("data/attractor_set_text.rds"), compress="gz")
```








