# hunting for attractors, source https://blog.k2h.se/post/hunting-for-attractors/

```{r setup}
library(tidyverse)
library(future)
library(furrr)
library(cluster)
library(cowplot)

plan(multisession)

# functions
source("R/attractors_functions.r")

# options
options(dplyr.summarise.inform=FALSE)
update_geom_defaults("point", list(size = 0.1, stroke = 0, shape = 16))

# parameters
scale_ink <- scale_color_gradientn(
  colors = c("white","grey60","#036564", "#033649", "#031634")
  ) 

scale_bg <- scale_colour_gradient(low="grey80", high="black")
scale_grey <- scale_colour_gradient(low="grey60", high="black")
scale_white <- scale_colour_gradient(low="grey60", high="white")

color_ink <- "#124270"
color_old <- "#FEFAEE"
```


```{r print_single, eval=FALSE}
table_set <- read_rds("data/attractor_parameter_set.rds")

list_selected_lines_01 <- c(
  75, 2364, 529,
  1820, 2691, 3066,
  3723, 4120, 4668,
  37513, 38286, 92261
)

list_selected_volume_01 <- c(
  683, 1269, 1594, # 976
  2213, 2527, 2670,
  3236, 3339, 4548, 18762, 70138
)

value_pattern <- 38286
footer <- paste(Sys.Date(), value_pattern)

# outputs with orbital-patterns 
plot_print <- table_set %>%
  filter(pattern == value_pattern) %>%
  compute_grid_data(iterations=2E6) %>% unnest(xy) %>% 
  ggplot(aes(x, y)) + 
  geom_point(alpha = 1/50, size = 0.5) +
  coord_equal() + theme_void() 

# outputs without orbital-patterns are better visualized with an estimation of point density
plot_print <- table_set %>%
  filter(pattern == value_pattern) %>%
  compute_print_data(a=.$a[[1]], iterations=3E6, gridsize=3000) %>% 
  ggplot(aes(x, y)) + 
  geom_point(aes(alpha = log(n), color = log(n)), size = 0.4) +
  scale_alpha_continuous(range = c(0, 1), limits = c(0, NA)) +
  scale_colour_gradient(low="grey100", high="black") +
  coord_equal() + theme_void() + theme(legend.position = "none")

# export
ggsave(
  plot_grid(plot_print) +
    draw_label(footer, x=0.99, y=0.01, hjust=1, size=6, color="black"),
  file=glue::glue("./R/figures/attractor_set_{value_pattern}.png"),
  dpi=300, width=295, height=210, scale=1, units="mm")

```


```{r print_shell, eval=FALSE}
table_set <- read_rds("data/attractor_parameter_set.rds")

list_selected_shell <- c(2213)

# series
name <- "shell"

data_print <- table_set %>%
  filter(pattern %in% !! sym(glue::glue("list_selected_{name}"))) %>% 
  mutate(
    data = future_map(a, compute_print_data, iteration=2E6, gridsize=3000),
    plot = map(data, render_print, scale_color=scale_white, size=0.4)
  )

hash_md5 <- digest::digest(data_print)
footer <- paste(Sys.Date(), substr(hash_md5, start = 1, stop = 7))

plot_print <- plot_grid(plotlist = rev(data_print$plot), ncol=1) + 
  draw_label(footer, x=0.99, y=0.01, hjust=1, size=6, color="white") +
  theme(panel.background = element_rect(fill = "black"))

# AX ratio : 6:8.5
ggsave(
  plot_print,
  file=glue::glue("./R/figures/attractor_set_{name}.png"),
  dpi=300, width=210, height=295, scale=1, units="mm")

```

```{r print_evolve, eval=FALSE}
table_set <- read_rds("data/attractor_parameter_set.rds")

list_selected_glyph <- c(8503, 23069)

list_selected_evolve <- c(22646, 21588, 10004, 1017)

# series
name <- "evolve"

data_print <- table_set %>%
  filter(pattern %in% !! sym(glue::glue("list_selected_{name}"))) %>% 
  mutate(
    data = future_map(a, compute_print_data, iteration=3E6, gridsize=3000),
    plot = map(data, render_print, scale_color=scale_bg, size=0.3)
  )

hash_md5 <- digest::digest(data_print)
footer <- paste(Sys.Date(), substr(hash_md5, start = 1, stop = 7))

plot_print <- plot_grid(plotlist = rev(data_print$plot), nrow=1) + 
  draw_label(footer, x=0.99, y=0.01, hjust=1, size=6, color="black") 

# AX ratio : 6:8.5 width=295, height=170
ggsave(
  plot_print,
  file=glue::glue("./R/figures/attractor_set_{name}.png"),
  dpi=300, width=295, height=170, scale=1, units="mm")

```

```{r print_example, eval=FALSE}
data_print <- compute_parallel_data(
  a = c(-0.38, -0.60,  0.20, -0.79,  0.10,  0.54,  0.41, -0.59,  0.95, -1.19, -0.65, -0.66),
  iterations = 4E6,
  gridsize = 1000)

plot_print <- data_print %>%
  ggplot(aes(x, y)) +
  geom_point(aes(alpha = sqrt(n), color = log(n)), size = 0, shape = 20) +
  scale_alpha_continuous(range = c(0, 1), limits = c(0, NA)) +
  scale_color_gradientn(colors = lapply(colourlovers::clpalette(292482)$colors, function(c) paste0('#', c))) +
  coord_equal()

ggsave(plot_print, file="./R/figures/attractor_01.png", dpi=300, width=6, height=8.5, scale=1)

data_print <- compute_parallel_data(
  a = c(-0.16, -0.37, -0.27, 0.16, -0.66, -0.74, -1.11, -0.51, 0.59, 0.81, -0.06, -0.44),
  iterations = 2000000,
  gridsize = 1000)

plot_print <- data_print %>%
  ggplot(aes(x, y)) +
    geom_point(aes(alpha = sqrt(n), color = sqrt(n)), size = 0, shape = 20) +
    scale_alpha_continuous(range = c(0, 1), limits = c(0, NA)) +
    scale_color_gradientn(
      colors = rev(lapply(colourlovers::clpalette(131576)$colors, function(c) paste0('#', c)))) +
    coord_equal()

ggsave(plot_print, file="./R/figures/attractor_02.png", dpi=200, width = 4, height = 6, scale = 1)
```

